# Generated by Django 4.2.3 on 2023-10-20 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CardInfo',
            new_name='Payment',
        ),
    ]
