# Generated by Django 4.2.3 on 2023-10-20 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_rename_cardinfo_payment'),
    ]

    operations = [
        migrations.CreateModel(
            name='feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Customer_name', models.CharField(max_length=100)),
                ('Customer_email', models.EmailField(max_length=254, unique=True)),
                ('title', models.CharField(max_length=100)),
                ('messsage', models.CharField(max_length=500)),
            ],
        ),
    ]
