# Generated by Django 4.2.3 on 2023-10-24 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0009_ordersummary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pizzainfo',
            name='user',
        ),
    ]
