# Generated by Django 4.2.3 on 2023-10-28 07:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('customer', '0012_alter_ordersummary_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ordersummary',
            options={},
        ),
        migrations.AlterModelManagers(
            name='ordersummary',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='ordersummary',
            name='user_ptr',
        ),
        migrations.AddField(
            model_name='ordersummary',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ordersummary',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
