# Generated by Django 4.2.3 on 2023-10-28 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0013_alter_ordersummary_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordersummary',
            name='user',
        ),
    ]
